global:
  scrape_interval: 10s # pull metrics interval
  evaluation_interval: 15s

rule_files:
  - rules/alert_rules.yml
  - rules/recording_rules.yml

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]